# Generated by Django 2.2.5 on 2022-03-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20220326_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='serves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_time', models.FloatField()),
                ('employeee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app1.employee')),
            ],
        ),
    ]
