# Generated by Django 2.2.5 on 2022-04-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_employee_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('manager', models.CharField(max_length=80)),
                ('discount', models.FloatField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='')),
                ('expiration_date', models.FloatField()),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='app1.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='serves',
            name='amount_time',
        ),
        migrations.RemoveField(
            model_name='serves',
            name='employeee',
        ),
        migrations.AddField(
            model_name='serves',
            name='numberOfTools',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='manager',
        ),
        migrations.AddField(
            model_name='serves',
            name='tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app1.tool'),
            preserve_default=False,
        ),
    ]
