# Generated by Django 2.2.5 on 2022-04-27 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20220424_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='tool',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tool',
            name='discription',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app1.category'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='company',
        ),
    ]
