# Generated by Django 2.2.5 on 2022-05-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_tool_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='category_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
