# Generated by Django 2.2.5 on 2022-05-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_tool_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='discription',
        ),
        migrations.AddField(
            model_name='category',
            name='discription',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
