# Generated by Django 2.2.5 on 2022-05-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20220502_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
