# Generated by Django 2.2.5 on 2022-05-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
